SET search_path = public, extensions;

-- Real content, read verbatim from EvoMentor DE's own source file
-- (data/basiskonzepte.json) -- not paraphrased, not AI-generated. Matched
-- to the real evomentor-thuringia project's own root Basiskonzepte by exact
-- label (same find-by-label discipline as migration 028's taxonomy harvest),
-- so this only ever updates a schema element that's really the Basiskonzept
-- it claims to be, never inserts a new one.

DO $$
DECLARE
  v_project_id UUID;
BEGIN
  SELECT id INTO v_project_id FROM projects WHERE slug = 'evomentor-thuringia';
  IF v_project_id IS NULL THEN RETURN; END IF;

  UPDATE lpm_schema_elements SET
    didactic_definition = 'Biologische Strukturen sind auf allen Organisationsebenen nicht zufällig geformt, sondern stehen durch natürliche Selektion in einem engen Zusammenhang mit ihrer jeweiligen Funktion – ohne dass dies zu einem optimalen oder perfekten Design führt, da Selektion stets nur unter den begrenzten Möglichkeiten bereits vorhandener Strukturen und Variation wirkt (evolutionäre Bastelei statt Ingenieursplanung). Das Verstehen dieses Zusammenhangs ermöglicht es, aus dem Bau eines biologischen Systems Rückschlüsse auf seine Funktion zu ziehen und umgekehrt. Dieses Basiskonzept ist das am häufigsten anwendbare Erklärungsprinzip im Biologieunterricht der Sekundarstufe I.',
    common_misconceptions = '[{"falsch": "Strukturen entstehen, weil ein Lebewesen sie ''braucht'' (teleologisches Denken)", "richtig": "Strukturen entstehen durch zufällige Variation und Selektion; Funktion ist das Ergebnis, nicht der Grund der Entstehung", "hinweis": "Teleologische Formulierungen im Unterricht bewusst aufgreifen und in evolutionäre Sprache umformulieren"}, {"falsch": "Funktion ist von Struktur unabhängig und kann beliebig variieren", "richtig": "Funktion ist kausal durch Struktur bedingt; Strukturveränderungen führen zu Funktionsveränderungen", "hinweis": "Pathologiebeispiele nutzen: Herzklappenfehler → Herzgeräusch; veränderte Enzymstruktur → Funktionsverlust"}, {"falsch": "Das Schlüssel-Schloss-Prinzip bedeutet absolute Starrheit der Molekülformen", "richtig": "Moleküle zeigen eine gewisse Flexibilität (induced fit), aber die Grundkomplementarität bleibt erhalten", "hinweis": "Für Klassen 7–8 ist die Schlüssel-Schloss-Vereinfachung pädagogisch angemessen; Induced-fit-Modell als mögliche Erweiterung"}, {"falsch": "Größere Oberfläche bedeutet immer bessere Funktion", "richtig": "Oberflächenvergrößerung muss mit anderen strukturellen Merkmalen (Durchblutung, Wanddicke, Transportmechanismen) kombiniert sein", "hinweis": "Alveolen: Oberfläche allein genügt nicht – auch dünne Wände und Kapillarnähe sind notwendig"}]'::jsonb,
    everyday_anchors = '{"Küchenschwamm: viele kleine Poren = große Oberfläche = bessere Wasseraufnahme → Alveolen, Darmzotten","Schlüssel und Schloss: Nur der passende Schlüssel öffnet das Schloss → Enzymspezifität, Antikörperspezifität","Wärmetauscher in der Heizung: Gegenstromprinzip → Niere, Kiemen","Fahrradhelm aus hartem Kunststoff: Schutz durch Materialeigenschaft → Insektenpanzer"}',
    core_principles = '{"Kompartimentierung","Morphologische und anatomische Angepasstheit","Schlüssel-Schloss-Prinzip","Oberflächenvergrößerung","Gegenspielerprinzip","Gegenstromprinzip"}'
  WHERE project_id = v_project_id AND parent_id IS NULL AND label = 'Struktur und Funktion';

  UPDATE lpm_schema_elements SET
    didactic_definition = 'Lebewesen sind keine geschlossenen Systeme, sondern stehen im ständigen Stoff- und Energieaustausch mit ihrer Umwelt. Dieser Austausch ist die materielle Grundlage aller Lebensprozesse. Das Konzept verbindet Chemie und Physik mit der Biologie und ist die Grundlage für das Verständnis von Verdauung, Atmung, Kreislauf, Zellatmung und Ökologie.',
    common_misconceptions = '[{"falsch": "Atmung (Gasaustausch) und Zellatmung (ATP-Produktion) sind dasselbe", "richtig": "Atmung bezeichnet den Gasaustausch auf Organismus-/Organebene; Zellatmung ist ein biochemischer Prozess in Mitochondrien auf Organell-/Molekülebene", "hinweis": "Systematische Unterscheidung der Ebenen: ''Wo passiert das genau?'' Immer explizit benennen"}, {"falsch": "Energie wird durch Essen erzeugt oder gespeichert und dann ''verbraucht''", "richtig": "Energie wird umgewandelt (chemische Energie in kinetische, thermische Energie); nichts wird erzeugt oder vernichtet", "hinweis": "Energieerhaltungssatz aus dem Physikunterricht explizit verknüpfen"}]'::jsonb,
    everyday_anchors = '{"Erschöpfung und Hunger nach Sport – was hat der Körper ''verbraucht''?","Wärmeentwicklung beim Sport – Energieentwertung spürbar machen","Verbrennungskerze: Sauerstoff wird verbraucht, CO₂ entsteht – wie in der Zellatmung","Hefe und Zucker: Gärung als Sonderfall der Energiegewinnung ohne Sauerstoff (Erweiterung)"}',
    core_principles = '{"Biologisches System als offenes System","Fließgleichgewicht","Stoffkreislauf und Energiefluss","Energieentwertung","Energetische Kopplung"}'
  WHERE project_id = v_project_id AND parent_id IS NULL AND label = 'Stoff- und Energieumwandlung';

  UPDATE lpm_schema_elements SET
    didactic_definition = 'Biologische Systeme verhalten sich zielgerichtet, weil sie Informationen verarbeiten. Das Nervensystem, das Hormonsystem und das Immunsystem sind drei verschiedene Implementierungen desselben grundlegenden Informationsarchitektur-Musters: Reiz → Rezeptor → Codierung → Weiterleitung → Verarbeitung → Reaktion.',
    common_misconceptions = '[{"falsch": "Das Nervensystem ''sendet Befehle'', das Hormonsystem ''macht etwas anderes''", "richtig": "Nerven- und Hormonsystem sind zwei verschiedene Implementierungen desselben Informationsprinzips", "hinweis": "Explizit vergleichen: Nervensystem (elektrisch, schnell, lokal) vs. Hormonsystem (chemisch, langsam, systemisch)"}, {"falsch": "Nerven transportieren ''Elektrizität'' wie Drähte", "richtig": "Das Aktionspotenzial ist ein elektrochemisches Phänomen durch Ionenflüsse über Membranen; keine Elektronenbewegung wie in Drähten", "hinweis": "Für Klassen 7–8: Aktionspotenzial als ''Erregungswelle'' beschreiben ohne Ionendetails"}, {"falsch": "Das Immunsystem ''weiß'' sofort, welcher Erreger eingedrungen ist", "richtig": "Das spezifische Immunsystem erkennt Antigene durch zufällig entstandene Antikörpervielfalt; Spezifität entsteht durch Selektion passender Antikörper, nicht durch Voraberkennung", "hinweis": "Schlüssel-Schloss-Prinzip auf Antigen-Antikörper übertragen; Gedächtniszellen als Lernprozess des Immunsystems"}]'::jsonb,
    everyday_anchors = '{"Kniescheibenreflex: Information ohne bewusste Verarbeitung","Schreck beim lauten Geräusch: Reiz → Reaktion ohne Nachdenken","Wut / Angst beim Sport: Adrenalin als Hormon wirkt auf viele Organe gleichzeitig","Impfschutz: Immunsystem ''merkt sich'' Erreger – biologisches Gedächtnis"}',
    core_principles = '{"Signaltransduktion","Codierung und Decodierung von Information","Kommunikation zwischen Organismen","Kommunikation innerhalb eines Organismus"}'
  WHERE project_id = v_project_id AND parent_id IS NULL AND label = 'Information und Kommunikation';

  UPDATE lpm_schema_elements SET
    didactic_definition = 'Biologische Systeme sind stabil, weil sie kontinuierlich über ihren Zustand informiert werden und korrigierend eingreifen können. Das Regelkreismodell (Sollwert, Istwert, Sensor, Komparator, Stellglied, Rückkopplung) ist das konzeptuelle Kernmodell dieses Basiskonzepts.',
    common_misconceptions = '[{"falsch": "Steuerung und Regelung sind synonyme Begriffe", "richtig": "Steuerung = offener Wirkungskreis, keine Rückmeldung, keine Selbstkorrektur. Regelung = geschlossener Wirkungskreis, Rückmeldung, Selbstkorrektur.", "hinweis": "Gegenbeispiel: Lichtschalter (Steuerung, kein Feedback) vs. Thermostat (Regelung mit Rückkopplung)"}, {"falsch": "Homöostase bedeutet, dass der Körper immer genau einen fixen Wert hält", "richtig": "Homöostase hält Werte in einem Toleranzbereich; kleine Schwankungen um den Sollwert sind normal und unvermeidlich", "hinweis": "Blutzuckerkurve über den Tag zeigen: nicht konstant, aber in Grenzen"}, {"falsch": "Insulin ''beseitigt'' Blutzucker", "richtig": "Insulin bewirkt, dass Glukose aus dem Blut in die Zellen aufgenommen wird; Blutzucker wird nicht ''beseitigt'', sondern umgeleitet", "hinweis": "Kausalkette: Insulin → Glukosetransporter → Zellaufnahme → Blutzucker sinkt"}]'::jsonb,
    everyday_anchors = '{"Thermostat / Raumtemperaturregelung: technisches Modell des biologischen Regelkreises","Körpertemperatur bei Fieber: Sollwert wird durch Pyrogene erhöht","Pupillenreflex bei Lichtwechsel: schnelle Steuerung, kein vollständiger Regelkreis","Hunger und Sättigung: grober Regelkreis der Energieaufnahme"}',
    core_principles = '{"Positive Rückkopplung (Rückwirkung)","Negative Rückkopplung (Rückwirkung)","Prinzip der Homöostase","Änderung eines inneren Zustands durch äußere Faktoren"}'
  WHERE project_id = v_project_id AND parent_id IS NULL AND label = 'Steuerung und Regelung';

  UPDATE lpm_schema_elements SET
    didactic_definition = 'Die individuelle Entwicklung beschreibt den Lebenslauf eines einzelnen Organismus als biologischen Prozess auf der Zeitskala eines einzelnen Lebens. Im Mittelpunkt stehen Zelldifferenzierung (wie entstehen aus einer Zelle viele verschiedene Zelltypen?), die hormonelle Steuerung von Reifung und Fortpflanzung sowie die vorgeburtliche Entwicklung. Besonders bedeutsam ist die Biologie des Menschen: die verlängerte Kindheitsphase, die postnatale Hirnentwicklung und das Immungedächtnis sind ontogenetische Besonderheiten, die erst durch ihre evolutive Entstehungsgeschichte (Basiskonzept Evolutive Entwicklung) vollständig erklärbar werden.',
    common_misconceptions = '[{"falsch": "Alle Körperzellen sind genetisch unterschiedlich, weil sie verschiedene Aufgaben haben", "richtig": "Alle Körperzellen eines Organismus haben (mit wenigen Ausnahmen) identisches Erbgut; Unterschiede entstehen durch verschiedene Genexpression (Zelldifferenzierung)", "hinweis": "Klonierungsbeispiel: Aus einer Körperzelle kann theoretisch ein ganzer Organismus entstehen"}, {"falsch": "Ontogenese und Phylogenese sind dasselbe oder haben nichts miteinander zu tun", "richtig": "Ontogenese (individuelle Entwicklung) ist die notwendige Grundlage für Phylogenese (evolutive Entwicklung), weil nur reproduktionsfähige Individuen genetische Information weitergeben können", "hinweis": "Explizit die Brücke bauen: Ohne Fortpflanzung keine Evolution; Fortpflanzung ist Teil der Ontogenese"}, {"falsch": "Das Gehirn ist bei der Geburt fertig und lernt nur durch Erfahrungen ''neue Inhalte''", "richtig": "Das Gehirn entwickelt sich strukturell nach der Geburt weiter: Synaptogenese, Pruning und Myelinisierung dauern bis ins frühe Erwachsenenalter; Lernen verändert die Synapsenstruktur physisch", "hinweis": "Verknüpfung mit Nervensystem-Plastizität und mit Suchtmittelwirkung als Beleg"}]'::jsonb,
    everyday_anchors = '{"Pubertät als eigene Erfahrung: Was hat sich verändert? Wann begann es?","Raupe wird zum Schmetterling: beobachtbare Metamorphose als Einstieg in Zelldifferenzierung","Eineiige Zwillinge: selbes Erbgut → warum werden sie trotzdem unterschiedlich?","Impfung als Eingriff in das Immungedächtnis: Immunsystem wird ''trainiert''"}',
    core_principles = '{"Zelldifferenzierung","Reproduktion und Individualentwicklung","Wachstum und Reifung"}'
  WHERE project_id = v_project_id AND parent_id IS NULL AND label = 'Individuelle Entwicklung';

  UPDATE lpm_schema_elements SET
    didactic_definition = 'Die evolutive Entwicklung beschreibt Veränderung auf der Zeitskala von Generationen bis Jahrmillionen und erfordert Populationsdenken statt Individualdenken. Sie ist zugleich das Basiskonzept, das erklärt, warum die anderen fünf Basiskonzepte in ihrer jeweiligen Form existieren: Strukturen, Stoffwechselwege, Kommunikationssysteme, Regelkreise und ontogenetische Programme sind selbst Produkte historisch-kontingenter Selektion, nicht optimal geplantes Design (Dobzhansky-Prinzip). Der Vokabular-Referenzrahmen für dieses Basiskonzept ist data/evolutionskonzepte.json.',
    common_misconceptions = '[{"falsch": "Selektion ''sucht'' oder ''wählt'' gezielt die besten Individuen aus", "richtig": "Selektion ist passiv: besser angepasste Individuen reproduzieren sich unter gegebenen Bedingungen häufiger; niemand ''wählt'' sie aus", "hinweis": "Formulierung: ''Individuen mit Merkmal X hinterlassen unter Bedingung Y mehr Nachkommen''"}, {"falsch": "Evolution ist gerichtet und hat ein Ziel (z. B. ''der Mensch ist das Ziel der Evolution'')", "richtig": "Evolution ist ungerichtet; Selektion wirkt auf den aktuellen Selektionsdruck, nicht auf ein zukünftiges Ziel", "hinweis": "Artenvielfalt der Insekten als Gegenbeispiel"}, {"falsch": "Ein Individuum kann sich im Laufe seines Lebens evolutiv anpassen (Lamarckismus)", "richtig": "Evolution betrifft Populationen über Generationen, nicht Individuen; erworbene Merkmale werden nicht vererbt", "hinweis": "Giraffenhals-Analogie ausführlich diskutieren"}]'::jsonb,
    everyday_anchors = '{"Hunderassen: extreme Formenvielfalt durch künstliche Selektion in kurzer Zeit","Antibiotikaresistenz: Evolution in Echtzeit","Schmetterlingssammlung: Variabilität innerhalb einer Art direkt beobachtbar","Fossilien: Lebewesen, die es heute nicht mehr gibt"}',
    core_principles = '{"Selektion","Genetische Variation durch Mutation und Rekombination","Entwicklung von Ökosystemen (ökologische Sukzession)"}'
  WHERE project_id = v_project_id AND parent_id IS NULL AND label = 'Evolutive Entwicklung';

END $$;
