SET search_path = public, extensions;

-- Imports the FULL, authoritative Unterkonzept vocabulary for all 6
-- Basiskonzepte, read directly from EvoMentor_DE's own source files
-- (data/evolutionskonzepte.json + the 5 "*konzepte.json" sibling files,
-- one per non-evolution Basiskonzept) -- not the reduced 70-row CSV subset
-- migration 028 imported. Verified directly against the real, live
-- evomentor-thuringia content before writing this: every one of the 1338
-- real basiskonzeptbezug[].relevante_unterkonzepte_taxonomie[]/
-- relevante_evolutionskonzepte_taxonomie[] tag values across all 305 real
-- Lernziele matches a label in THIS vocabulary (scoped to its correct root
-- Basiskonzept) -- a 100% match, confirming this is genuinely what the
-- original Lernziele tagging was written against, not the CSV. See design
-- note lab_manager/docs/design-notes/openlpm-basiskonzepte-subconcept-
-- taxonomy-broken-links-2026-10-01.md for the full investigation.
--
-- Deliberately additive and idempotent, same discipline as migration 028:
-- every row is found-or-created by (label, parent), never assumed to
-- already exist at a specific id. Four of these Ebene-1 labels
-- ("Steuerung", "Regelung", "Stoffumwandlung", "Energieumwandlung")
-- already exist as root-level rows from the ORIGINAL EvoMentor_DE import
-- (data/basiskonzepte.json's own "teilkonzepte", 2 per Basiskonzept) --
-- this migration finds those existing rows and nests their real Ebene-2
-- children underneath them (they had none before), rather than creating
-- duplicates. A 5th teilkonzept label ("Zelldifferenzierung und
-- Embryonalentwicklung") exact-matches a real Ebene-1 entry here too, same
-- treatment. Every row's definition/beispiel is kept in sync via UPDATE
-- even when the row already existed, so re-running this after a manual
-- edit is still safe (no destructive effect beyond refreshing these two
-- fields back to the source text).
--
-- The remaining 7 teilkonzepte labels (Struktur, Funktion, Information,
-- Kommunikation, Hormonelle Reifung und erworbene Anpassungsfähigkeit,
-- Variation, Angepasstheit und Selektion, Stammesgeschichte und
-- vergleichende Systeme) don't correspond to any node in this richer
-- vocabulary and have zero real tag usage (checked directly) -- left
-- untouched here, not deprecated; that's a separate, optional cleanup
-- decision, not bundled into this import.

DO $$
DECLARE
  v_project_id UUID;
  r RECORD;
  v_root_id UUID;
  v_e1_id UUID;
BEGIN
  SELECT id INTO v_project_id FROM projects WHERE slug = 'evomentor-thuringia';
  IF v_project_id IS NULL THEN
    RAISE NOTICE 'evomentor-thuringia project not found -- skipping import';
    RETURN;
  END IF;

  CREATE TEMP TABLE _concept_import (
    root_label TEXT, e1_label TEXT, e1_def TEXT, e1_ex TEXT, e1_order INT,
    e2_label TEXT, e2_def TEXT, e2_ex TEXT, e2_order INT
  ) ON COMMIT DROP;

  INSERT INTO _concept_import (root_label, e1_label, e1_def, e1_ex, e1_order, e2_label, e2_def, e2_ex, e2_order) VALUES
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'genetische Variation', 'Unterschiede in der DNA-Sequenz zwischen Individuen einer Population, entstanden durch Mutation, Rekombination und Gentransfer.', 'Unterschiedliche Blutgruppen oder Fellfarb-Allele innerhalb einer Population.', 1),
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'phänotypische Variation', 'Sichtbare Unterschiede in Merkmalen zwischen Individuen, die auf genetischer Variation, Umwelteinflüssen oder deren Zusammenspiel beruhen.', 'Unterschiedliche Körpergröße oder Blattform innerhalb einer Pflanzenart.', 2),
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'Modifikation', 'Nicht erbliche, umweltbedingte Veränderung des Phänotyps innerhalb der durch das Genom vorgegebenen Reaktionsnorm.', 'Bräunung der Haut durch UV-Strahlung; unterschiedliche Blattgröße derselben Pflanze in Sonne und Schatten.', 3),
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'Rekombination', 'Neukombination elterlicher Allele bei der sexuellen Fortpflanzung (Meiose, Crossing-over), eine zentrale Quelle genetischer Variation ohne neue Mutationen.', 'Geschwister mit unterschiedlichen Merkmalskombinationen derselben Eltern.', 4),
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'Gentransfer', 'Übertragung genetischen Materials zwischen Organismen außerhalb der vertikalen Vererbung (horizontaler Gentransfer), besonders bedeutsam bei Bakterien.', 'Übertragung von Antibiotikaresistenz-Genen zwischen Bakterienstämmen über Plasmide.', 5),
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'Epigenetik', 'Vererbbare Veränderungen der Genaktivität (z. B. durch DNA-Methylierung), die nicht auf einer Änderung der DNA-Sequenz selbst beruhen.', 'Unterschiedliche Genexpression bei genetisch identischen Bienen (Königin vs. Arbeiterin) durch Fütterung.', 6),
  ('Evolutive Entwicklung', 'Variation und Diversität', 'Innerhalb jeder Population unterscheiden sich Individuen in ihren Merkmalen – genetisch, phänotypisch und im Verhalten. Diese Variation ist die notwendige Voraussetzung für jede Form von Selektion und damit für Evolution überhaupt.', 'Schneckenhäuser derselben Art unterscheiden sich in Farbe und Bänderung; Unterrichtsbezug: Artenvergleich, Erweiterung der Artenkenntnis.', 1, 'Phänotypische Plastizität', 'Die Fähigkeit eines Genotyps, je nach Umweltbedingungen unterschiedliche Phänotypen auszubilden.', 'Wasserflöhe (Daphnia) bilden bei Anwesenheit von Fraßfeinden schützende ''Helme'' aus.', 7),
  ('Evolutive Entwicklung', 'Vererbung von Merkmalen', 'Weitergabe von Merkmalen von einer Generation an die nächste über verschiedene, teils nicht-genetische Kanäle.', 'Kinder ähneln ihren Eltern nicht nur genetisch, sondern z. B. auch in erlernten Verhaltensweisen.', 2, 'genetische Vererbung', 'Weitergabe von Merkmalen über die DNA-Sequenz von Eltern an Nachkommen.', 'Vererbung der Blutgruppe oder von Erbkrankheiten.', 1),
  ('Evolutive Entwicklung', 'Vererbung von Merkmalen', 'Weitergabe von Merkmalen von einer Generation an die nächste über verschiedene, teils nicht-genetische Kanäle.', 'Kinder ähneln ihren Eltern nicht nur genetisch, sondern z. B. auch in erlernten Verhaltensweisen.', 2, 'epigenetische Vererbung', 'Weitergabe von Genaktivitätsmustern (nicht der DNA-Sequenz selbst) über Generationen hinweg.', 'Auswirkungen mütterlicher Ernährung während der Schwangerschaft auf die Genregulation der Nachkommen.', 2),
  ('Evolutive Entwicklung', 'Vererbung von Merkmalen', 'Weitergabe von Merkmalen von einer Generation an die nächste über verschiedene, teils nicht-genetische Kanäle.', 'Kinder ähneln ihren Eltern nicht nur genetisch, sondern z. B. auch in erlernten Verhaltensweisen.', 2, 'soziale/kulturelle Vererbung', 'Weitergabe von Verhaltensweisen, Wissen und Fertigkeiten durch Beobachtung, Nachahmung und Lehren statt über die Gene.', 'Werkzeuggebrauch bei Schimpansen, der innerhalb einer Gruppe von Generation zu Generation weitergegeben wird.', 3),
  ('Evolutive Entwicklung', 'Vererbung von Merkmalen', 'Weitergabe von Merkmalen von einer Generation an die nächste über verschiedene, teils nicht-genetische Kanäle.', 'Kinder ähneln ihren Eltern nicht nur genetisch, sondern z. B. auch in erlernten Verhaltensweisen.', 2, 'ökologische Vererbung', 'Weitergabe einer von den Eltern veränderten Umwelt (statt genetischer Information) als Vererbungskanal, eng verknüpft mit Nischenkonstruktion.', 'Ein Biberdamm bzw. Bau, den nachfolgende Bibergenerationen übernehmen und weiter nutzen.', 4),
  ('Evolutive Entwicklung', 'Natürliche Selektion und Selektionsdruck', 'Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich unter gegebenen Umweltbedingungen häufiger fort; dieser Unterschied im Fortpflanzungserfolg treibt die Veränderung von Populationen über Generationen.', 'Birkenspanner: dunklere Falter wurden während der Industrialisierung durch Vogelfraß seltener erbeutet als helle.', 3, 'stabilisierende Selektion', 'Selektion, die extreme Merkmalsausprägungen benachteiligt und den mittleren Bereich einer Merkmalsverteilung begünstigt.', 'Geburtsgewicht beim Menschen: sehr niedriges und sehr hohes Gewicht ist mit höherer Sterblichkeit verbunden.', 1),
  ('Evolutive Entwicklung', 'Natürliche Selektion und Selektionsdruck', 'Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich unter gegebenen Umweltbedingungen häufiger fort; dieser Unterschied im Fortpflanzungserfolg treibt die Veränderung von Populationen über Generationen.', 'Birkenspanner: dunklere Falter wurden während der Industrialisierung durch Vogelfraß seltener erbeutet als helle.', 3, 'gerichtete Selektion', 'Selektion, die ein Extrem einer Merkmalsverteilung begünstigt und den Mittelwert der Population über Generationen in eine Richtung verschiebt.', 'Zunehmende Schnabelgröße bei Darwinfinken während trockener Jahre mit harten Samen.', 2),
  ('Evolutive Entwicklung', 'Natürliche Selektion und Selektionsdruck', 'Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich unter gegebenen Umweltbedingungen häufiger fort; dieser Unterschied im Fortpflanzungserfolg treibt die Veränderung von Populationen über Generationen.', 'Birkenspanner: dunklere Falter wurden während der Industrialisierung durch Vogelfraß seltener erbeutet als helle.', 3, 'balancierende Selektion', 'Selektionsform, die genetische Variation in einer Population aktiv erhält, etwa weil heterozygote Individuen im Vorteil sind.', 'Sichelzellanlage: heterozygote Träger sind vor Malaria geschützt, ohne die Krankheit selbst auszubilden.', 3),
  ('Evolutive Entwicklung', 'Natürliche Selektion und Selektionsdruck', 'Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich unter gegebenen Umweltbedingungen häufiger fort; dieser Unterschied im Fortpflanzungserfolg treibt die Veränderung von Populationen über Generationen.', 'Birkenspanner: dunklere Falter wurden während der Industrialisierung durch Vogelfraß seltener erbeutet als helle.', 3, 'frequenzabhängige Selektion', 'Der Selektionsvorteil eines Merkmals hängt davon ab, wie häufig es in der Population bereits vorkommt.', 'Seltene Beutefarbmuster werden von Fressfeinden seltener erkannt und dadurch begünstigt (apostatische Selektion).', 4),
  ('Evolutive Entwicklung', 'Natürliche Selektion und Selektionsdruck', 'Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich unter gegebenen Umweltbedingungen häufiger fort; dieser Unterschied im Fortpflanzungserfolg treibt die Veränderung von Populationen über Generationen.', 'Birkenspanner: dunklere Falter wurden während der Industrialisierung durch Vogelfraß seltener erbeutet als helle.', 3, 'Trade-offs/Zielkonflikte', 'Evolutionäre Kompromisse, bei denen ein Merkmal in einer Hinsicht vorteilhaft, in anderer Hinsicht nachteilig ist, sodass kein Merkmal alle Anforderungen gleichzeitig optimieren kann.', 'Große Geweihe bei Hirschen erhöhen den Fortpflanzungserfolg, verringern aber die Beweglichkeit vor Fressfeinden.', 5),
  ('Evolutive Entwicklung', 'Natürliche Selektion und Selektionsdruck', 'Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich unter gegebenen Umweltbedingungen häufiger fort; dieser Unterschied im Fortpflanzungserfolg treibt die Veränderung von Populationen über Generationen.', 'Birkenspanner: dunklere Falter wurden während der Industrialisierung durch Vogelfraß seltener erbeutet als helle.', 3, 'sexuelle Selektion', 'Selektion durch unterschiedlichen Fortpflanzungserfolg, die aus Partnerwahl oder Konkurrenz um Paarungspartner resultiert, unabhängig vom Überlebensvorteil.', 'Das auffällige Pfauenrad, das Weibchen bei der Partnerwahl bevorzugen.', 6),
  ('Evolutive Entwicklung', 'Fitness', 'Maß für den relativen Beitrag eines Genotyps/Phänotyps zum Genpool der nächsten Generation, bestimmt durch Überleben und Fortpflanzungserfolg – nicht zu verwechseln mit körperlicher Fitness im Alltagssinn.', 'Ein Individuum mit vielen überlebensfähigen Nachkommen hat eine hohe biologische Fitness, unabhängig von seiner Körperkraft.', 4, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Anpassung und Angepasstheit', 'Merkmale, die durch natürliche Selektion entstanden sind, weil sie das Überleben oder den Fortpflanzungserfolg in einer bestimmten Umwelt erhöht haben.', 'Das Fell des Eisbären als Anpassung an arktische Kälte.', 5, 'Funktion von Merkmalen', 'Die durch Selektion erklärbare biologische Leistung, die ein Merkmal für seinen Träger erbringt.', 'Die Funktion der Tarnfarbe eines Insekts besteht im Schutz vor Fressfeinden.', 1),
  ('Evolutive Entwicklung', 'Anpassung und Angepasstheit', 'Merkmale, die durch natürliche Selektion entstanden sind, weil sie das Überleben oder den Fortpflanzungserfolg in einer bestimmten Umwelt erhöht haben.', 'Das Fell des Eisbären als Anpassung an arktische Kälte.', 5, 'Exaptation (Umfunktionieren von Merkmalen)', 'Ein Merkmal, das ursprünglich für eine andere Funktion entstand (oder ohne Funktion war) und im Laufe der Evolution eine neue Funktion übernommen hat.', 'Vogelfedern entstanden vermutlich zur Wärmeisolation und wurden erst später für den Flug genutzt.', 2),
  ('Evolutive Entwicklung', 'Anpassung und Angepasstheit', 'Merkmale, die durch natürliche Selektion entstanden sind, weil sie das Überleben oder den Fortpflanzungserfolg in einer bestimmten Umwelt erhöht haben.', 'Das Fell des Eisbären als Anpassung an arktische Kälte.', 5, 'Evolutionäres Mismatch', 'Eine Anpassung passt nicht mehr zur aktuellen Umwelt, weil sich diese schneller verändert hat als die biologische Anpassung selbst (z. B. durch kulturellen Wandel).', 'Der Heißhunger auf Zucker und Fett war in Zeiten von Nahrungsknappheit vorteilhaft, führt im heutigen Nahrungsüberfluss aber zu Übergewicht.', 3),
  ('Evolutive Entwicklung', 'Gendrift', 'Zufällige Veränderung der Allelhäufigkeiten in einer Population von Generation zu Generation, unabhängig von Selektionsvorteilen; wirkt besonders stark in kleinen Populationen.', 'Ein zufälliges Ereignis (z. B. ein Sturm) dezimiert eine kleine Population und verändert dadurch zufällig die Allelhäufigkeiten der Überlebenden.', 6, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Migration/Genfluss', 'Austausch genetischen Materials zwischen Populationen durch Zu- und Abwanderung von Individuen; wirkt Differenzierung zwischen Populationen entgegen.', 'Wandernde Wölfe bringen neue Allele in eine bislang isolierte Population ein.', 7, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Flaschenhalseffekt', 'Starke, plötzliche Verringerung der genetischen Vielfalt einer Population durch ein Ereignis, das nur einen kleinen, nicht-repräsentativen Teil der Population überleben lässt.', 'Geparden weisen aufgrund eines historischen Flaschenhalses eine außergewöhnlich geringe genetische Vielfalt auf.', 8, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Gründereffekt', 'Verringerte genetische Vielfalt einer neu gegründeten Population, die von einer kleinen Anzahl von Gründerindividuen einer größeren Ursprungspopulation abstammt.', 'Erhöhte Häufigkeit bestimmter Erbkrankheiten in isolierten Inselpopulationen, die auf wenige Erstsiedler zurückgehen.', 9, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Lebensgeschichte / Life-History-Theorie', 'Theorie über die evolutionäre Optimierung des zeitlichen Ablaufs von Wachstum, Fortpflanzung und Alterung eines Organismus unter begrenzten Ressourcen (Trade-off zwischen Anzahl und Investition pro Nachkommen).', 'Arten mit vielen, wenig umsorgten Nachkommen (r-Strategen) im Vergleich zu Arten mit wenigen, intensiv umsorgten Nachkommen (K-Strategen).', 10, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Koevolution', 'Wechselseitige evolutionäre Anpassung zweier oder mehrerer Arten aneinander, bei der Veränderungen der einen Art Selektionsdruck auf die andere ausüben.', 'Blüten und ihre spezialisierten Bestäuber entwickeln passgenaue Formen aneinander angepasst.', 11, 'Domestikation', 'Ein Sonderfall der Koevolution, bei dem der Mensch durch gezielte oder unbewusste künstliche Selektion die Evolution von Nutz- und Haustierarten lenkt.', 'Die Züchtung verschiedener Hunderassen aus dem Wolf durch den Menschen.', 1),
  ('Evolutive Entwicklung', 'Nischenkonstruktion', 'Organismen verändern aktiv ihre Umwelt und damit die Selektionsbedingungen für sich selbst und andere Arten.', 'Biber bauen Dämme und verändern dadurch ihren eigenen und den Lebensraum vieler anderer Arten grundlegend.', 12, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Multilevel-Selektion', 'Selektion kann gleichzeitig auf mehreren biologischen Organisationsebenen wirken – von Genen über Zellen und Individuen bis zu Gruppen.', 'Der Übergang von Einzellern zu Vielzellern erforderte, dass Selektion auf Zellebene teilweise durch Selektion auf Organismusebene ersetzt wurde.', 13, 'Endosymbiontentheorie', 'Theorie, wonach Mitochondrien und Chloroplasten aus einst frei lebenden Bakterien hervorgingen, die von Vorläufern eukaryotischer Zellen aufgenommen wurden und zu Zellorganellen wurden.', 'Mitochondrien besitzen eigene, bakterienähnliche DNA als Beleg ihrer symbiontischen Herkunft.', 1),
  ('Evolutive Entwicklung', 'Multilevel-Selektion', 'Selektion kann gleichzeitig auf mehreren biologischen Organisationsebenen wirken – von Genen über Zellen und Individuen bis zu Gruppen.', 'Der Übergang von Einzellern zu Vielzellern erforderte, dass Selektion auf Zellebene teilweise durch Selektion auf Organismusebene ersetzt wurde.', 13, 'Evolution von Einzellern zu Vielzellern', 'Der mehrfach unabhängig vollzogene evolutionäre Übergang von einzelligen zu vielzelligen Organismen mit spezialisierten, kooperierenden Zellen.', 'Kolonienbildende Grünalgen wie Volvox als Übergangsform zwischen Einzeller und echtem Vielzeller.', 2),
  ('Evolutive Entwicklung', 'Multilevel-Selektion', 'Selektion kann gleichzeitig auf mehreren biologischen Organisationsebenen wirken – von Genen über Zellen und Individuen bis zu Gruppen.', 'Der Übergang von Einzellern zu Vielzellern erforderte, dass Selektion auf Zellebene teilweise durch Selektion auf Organismusebene ersetzt wurde.', 13, 'Verwandtenselektion', 'Selektion, die altruistisches Verhalten gegenüber genetisch verwandten Individuen begünstigt, weil dadurch anteilig eigene Gene weitergegeben werden (Verwandtschaftsgrad × Nutzen > Kosten).', 'Arbeiterinnen bei sozialen Insekten verzichten auf eigene Fortpflanzung und ziehen stattdessen Geschwister auf.', 3),
  ('Evolutive Entwicklung', 'Multilevel-Selektion', 'Selektion kann gleichzeitig auf mehreren biologischen Organisationsebenen wirken – von Genen über Zellen und Individuen bis zu Gruppen.', 'Der Übergang von Einzellern zu Vielzellern erforderte, dass Selektion auf Zellebene teilweise durch Selektion auf Organismusebene ersetzt wurde.', 13, 'Evolution von Kooperation/Altruismus', 'Erklärung, wie kooperatives und scheinbar selbstloses Verhalten trotz individueller Kosten durch Selektion entstehen und stabil bleiben kann.', 'Wechselseitige Fellpflege bei Primaten, die auf Gegenseitigkeit (reziproker Altruismus) beruht.', 4),
  ('Evolutive Entwicklung', 'Multilevel-Selektion', 'Selektion kann gleichzeitig auf mehreren biologischen Organisationsebenen wirken – von Genen über Zellen und Individuen bis zu Gruppen.', 'Der Übergang von Einzellern zu Vielzellern erforderte, dass Selektion auf Zellebene teilweise durch Selektion auf Organismusebene ersetzt wurde.', 13, 'Evolutionäre Prozesse innerhalb von Organismen', 'Selektionsähnliche Prozesse, die innerhalb eines einzelnen Organismus zwischen Zellen oder Zelllinien ablaufen.', 'Somatische Selektion zwischen B-Zell-Klonen im Immunsystem während der Antikörperreifung; Tumorentstehung als Selektion zwischen Zelllinien.', 5),
  ('Evolutive Entwicklung', 'Tiefenzeit', 'Die Vorstellung von den enormen, für die Alltagserfahrung kaum fassbaren Zeiträumen der Erd- und Lebensgeschichte, die evolutive Veränderungen erst ermöglichen.', 'Der Vergleich der Erdgeschichte mit einem einzigen Kalenderjahr, in dem die gesamte Menschheitsgeschichte erst in den letzten Sekunden des 31. Dezembers stattfindet.', 14, 'geologische Epochen', 'Die Gliederung der Erdgeschichte in Zeitabschnitte (z. B. Kambrium, Kreide, Känozoikum), die den Rahmen für die Einordnung evolutionärer Ereignisse liefert.', 'Die ''kambrische Explosion'' als Zeitabschnitt rascher Diversifizierung vielzelliger Tierstämme.', 1),
  ('Evolutive Entwicklung', 'Tiefenzeit', 'Die Vorstellung von den enormen, für die Alltagserfahrung kaum fassbaren Zeiträumen der Erd- und Lebensgeschichte, die evolutive Veränderungen erst ermöglichen.', 'Der Vergleich der Erdgeschichte mit einem einzigen Kalenderjahr, in dem die gesamte Menschheitsgeschichte erst in den letzten Sekunden des 31. Dezembers stattfindet.', 14, 'Fossilien', 'Erhaltene Überreste oder Spuren vergangener Lebewesen, die direkte materielle Belege für die Geschichte des Lebens und seine Veränderung über die Zeit liefern.', 'Ammoniten als Leitfossilien zur Datierung von Gesteinsschichten.', 2),
  ('Evolutive Entwicklung', 'Tiefenzeit', 'Die Vorstellung von den enormen, für die Alltagserfahrung kaum fassbaren Zeiträumen der Erd- und Lebensgeschichte, die evolutive Veränderungen erst ermöglichen.', 'Der Vergleich der Erdgeschichte mit einem einzigen Kalenderjahr, in dem die gesamte Menschheitsgeschichte erst in den letzten Sekunden des 31. Dezembers stattfindet.', 14, 'Übergangsformen/Entwicklungslinien', 'Fossilfunde, die Merkmale sowohl einer Vorläufer- als auch einer Nachfolgergruppe kombinieren und damit stufenweise evolutive Übergänge belegen.', 'Archaeopteryx mit Merkmalen sowohl von Reptilien (Zähne, langer knöcherner Schwanz) als auch von Vögeln (Federn).', 3),
  ('Evolutive Entwicklung', 'Stammbäume und phylogenetische Systematik', 'Die grafische und methodische Darstellung von Verwandtschaftsverhältnissen zwischen Taxa auf Grundlage gemeinsamer abgeleiteter Merkmale.', 'Ein Kladogramm der Wirbeltiergruppen, das Verzweigungspunkte gemeinsamer Vorfahren zeigt.', 15, 'gemeinsame Abstammung/Verwandtschaft', 'Das Grundprinzip, dass alle heutigen Arten von gemeinsamen Vorfahren abstammen und dadurch in einem einzigen, verzweigten Lebensbaum miteinander verbunden sind.', 'Menschen und Schimpansen teilen einen gemeinsamen Vorfahren, der vor etwa 6-7 Millionen Jahren lebte.', 1),
  ('Evolutive Entwicklung', 'Konservierung von Merkmalen (gemeinsame genetische Grundlagen, Baupläne, Entwicklungsprozesse usw.)', 'Grundlegende genetische Steuerungsmechanismen, Körperbaupläne und Entwicklungsprozesse bleiben über sehr lange evolutionäre Zeiträume und weit auseinanderliegende Tiergruppen hinweg erstaunlich ähnlich.', 'Hox-Gene steuern die Körperachsengliederung sowohl bei Fruchtfliegen als auch beim Menschen in vergleichbarer Weise.', 16, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Homologie und Analogie/Konvergente und divergente Evolution', 'Homologe Strukturen gehen auf ein gemeinsames Grundmuster eines Vorfahren zurück (divergente Evolution), analoge Strukturen sind unabhängig voneinander funktionell ähnlich entstanden (konvergente Evolution).', 'Der Vordergliedmaßenbau von Fledermausflügel, Walflosse und Menschenarm ist homolog; Fledermausflügel und Insektenflügel sind dagegen analog.', 17, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Artbildung und adaptive Radiation', 'Der Prozess, durch den aus einer Ausgangsart eine oder mehrere neue Arten entstehen, oft durch geografische Isolation; adaptive Radiation bezeichnet die rasche Aufspaltung in viele ökologisch spezialisierte Arten.', 'Die Darwinfinken der Galápagos-Inseln, die sich aus einer Stammart in viele auf unterschiedliche Nahrungsquellen spezialisierte Arten aufgespalten haben.', 18, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Aussterben', 'Das endgültige Verschwinden einer Art, wenn kein Individuum mehr überlebt; ein integraler, ständig ablaufender Teil der Evolutionsgeschichte, der durch Massenaussterben-Ereignisse stark beschleunigt sein kann.', 'Das Aussterben der nicht-avischen Dinosaurier am Ende der Kreidezeit.', 19, NULL, NULL, NULL, NULL),
  ('Evolutive Entwicklung', 'Evolutionäre Entwicklungsbiologie (Evo-Devo)', 'Forschungsrichtung, die untersucht, wie Veränderungen in den genetischen Steuerungsprogrammen der individuellen Entwicklung (Ontogenese) zu evolutionären Veränderungen von Körperbauplänen führen.', 'Unterschiede in der Ausprägung von Hox-Genen erklären die verschiedene Anzahl von Körpersegmenten bei Insekten.', 20, 'biogenetische Grundregel', 'Haeckels historische, in ihrer strengen Form widerlegte These, die Individualentwicklung (Ontogenese) wiederhole die Stammesgeschichte (Phylogenese); im modernen Evo-Devo-Verständnis ersetzt durch die Erkenntnis geteilter, aber modifizierter Entwicklungsprogramme.', 'Kiemenspalten-ähnliche Strukturen im menschlichen Embryo als Hinweis auf gemeinsame Entwicklungsprogramme mit Fischen, nicht als wörtliche Wiederholung der Stammesgeschichte.', 1),
  ('Evolutive Entwicklung', 'kulturelle Evolution', 'Die Veränderung von Wissen, Verhaltensweisen, Werkzeugen und sozialen Praktiken über Generationen durch Lernen, Weitergabe und Selektion kultureller Varianten – analog zur biologischen Evolution, aber mit eigenen Mechanismen (z. B. schnellerer, teils gerichteter Weitergabe).', 'Die rasche weltweite Verbreitung und Weiterentwicklung landwirtschaftlicher Techniken innerhalb weniger Generationen.', 21, NULL, NULL, NULL, NULL),
  ('Individuelle Entwicklung', 'Zelldifferenzierung und Embryonalentwicklung', 'Aus einer befruchteten Eizelle entstehen durch wiederholte Zellteilung und zunehmende Spezialisierung (Differenzierung) die unterschiedlichen Zelltypen, Gewebe und Organe eines vielzelligen Organismus.', 'Aus einer befruchteten Eizelle entwickeln sich über Furchung, Gastrulation und Organogenese Nerven-, Muskel- und Hautzellen, obwohl alle dasselbe Genom besitzen.', 1, 'Zelldifferenzierung', 'Der Prozess, durch den zunächst gleichartige, unspezialisierte Zellen unterschiedliche Genexpressionsmuster ausbilden und sich dadurch strukturell und funktionell spezialisieren.', 'Aus omnipotenten Stammzellen des frühen Embryos entstehen spezialisierte Muskel-, Nerven- und Blutzellen mit jeweils eigenem Aufgabenprofil.', 1),
  ('Individuelle Entwicklung', 'Zelldifferenzierung und Embryonalentwicklung', 'Aus einer befruchteten Eizelle entstehen durch wiederholte Zellteilung und zunehmende Spezialisierung (Differenzierung) die unterschiedlichen Zelltypen, Gewebe und Organe eines vielzelligen Organismus.', 'Aus einer befruchteten Eizelle entwickeln sich über Furchung, Gastrulation und Organogenese Nerven-, Muskel- und Hautzellen, obwohl alle dasselbe Genom besitzen.', 1, 'Embryonalentwicklung (Furchung, Gastrulation, Organogenese)', 'Die frühe Individualentwicklung von der befruchteten Eizelle bis zur Anlage der Organe, gegliedert in aufeinanderfolgende Phasen: Furchung (Zellteilungen ohne Wachstum), Gastrulation (Bildung der Keimblätter) und Organogenese (Entstehung der Organanlagen).', 'Beim Hühnerembryo lassen sich Furchungsstadien, die Bildung der drei Keimblätter und die anschließende Anlage von Herz und Neuralrohr im Zeitverlauf beobachten.', 2),
  ('Individuelle Entwicklung', 'Lebenszyklus', 'Die charakteristische Abfolge von Entwicklungsstadien, die ein Organismus von der Befruchtung bis zur eigenen Fortpflanzungsfähigkeit durchläuft — bei manchen Arten kontinuierlich, bei anderen über qualitativ unterschiedliche Stadien mit tiefgreifender Umgestaltung.', 'Der Lebenszyklus des Grasfroschs umfasst Ei, wasserlebende Kaulquappe mit Kiemen und Schwanz sowie das landlebende Adulttier mit Lunge und Beinen.', 2, 'Metamorphose (vollständige/unvollständige Verwandlung)', 'Eine tiefgreifende, meist hormonell gesteuerte Umgestaltung der Körperform während der individuellen Entwicklung, bei der sich Larven- und Adultstadium in Gestalt und Lebensweise deutlich unterscheiden. Bei Insekten wird zwischen vollständiger Metamorphose (mit Puppenstadium) und unvollständiger Metamorphose (ohne Puppenstadium) unterschieden.', 'Der Schmetterling durchläuft mit Ei, Raupe, Puppe und Falter eine vollständige Metamorphose; die Heuschrecke mit Ei, Larve und Adulttier eine unvollständige.', 1),
  ('Individuelle Entwicklung', 'Lebenszyklus', 'Die charakteristische Abfolge von Entwicklungsstadien, die ein Organismus von der Befruchtung bis zur eigenen Fortpflanzungsfähigkeit durchläuft — bei manchen Arten kontinuierlich, bei anderen über qualitativ unterschiedliche Stadien mit tiefgreifender Umgestaltung.', 'Der Lebenszyklus des Grasfroschs umfasst Ei, wasserlebende Kaulquappe mit Kiemen und Schwanz sowie das landlebende Adulttier mit Lunge und Beinen.', 2, 'Direkte und indirekte Entwicklung', 'Bei direkter Entwicklung ähnelt das Jungtier von Beginn an dem erwachsenen Tier und wächst im Wesentlichen nur heran; bei indirekter Entwicklung durchläuft der Organismus ein oder mehrere Larvenstadien, die sich morphologisch und ökologisch deutlich vom Adulttier unterscheiden.', 'Ein Wolfsjunges entwickelt sich direkt zum erwachsenen Wolf; ein Frosch entwickelt sich indirekt über das Kaulquappenstadium.', 2),
  ('Individuelle Entwicklung', 'Wachstum und Alterung', 'Die kontinuierliche quantitative Zunahme von Körpergröße und -masse während der Entwicklung sowie die im späteren Lebensverlauf einsetzende, fortschreitende Abnahme der Funktionsfähigkeit von Zellen, Geweben und Organen.', 'Die Wachstumskurve eines Menschen zeigt Phasen beschleunigten Wachstums (Säuglingsalter, Pubertät), gefolgt von einer im Erwachsenenalter einsetzenden allmählichen Abnahme der Organleistungsfähigkeit.', 3, 'Wachstum', 'Die Zunahme von Zellzahl (Zellteilung) und/oder Zellgröße eines Organismus über die Zeit, häufig ungleichmäßig auf verschiedene Körperregionen und Lebensphasen verteilt.', 'Der menschliche Kopf wächst pränatal und postnatal deutlich langsamer als die Extremitäten — ein Neugeborenes hat proportional einen viel größeren Kopf als ein Erwachsener.', 1),
  ('Individuelle Entwicklung', 'Wachstum und Alterung', 'Die kontinuierliche quantitative Zunahme von Körpergröße und -masse während der Entwicklung sowie die im späteren Lebensverlauf einsetzende, fortschreitende Abnahme der Funktionsfähigkeit von Zellen, Geweben und Organen.', 'Die Wachstumskurve eines Menschen zeigt Phasen beschleunigten Wachstums (Säuglingsalter, Pubertät), gefolgt von einer im Erwachsenenalter einsetzenden allmählichen Abnahme der Organleistungsfähigkeit.', 3, 'Seneszenz/Alterung', 'Die im Laufe des Lebens fortschreitende Abnahme der Zell- und Organfunktion, die die Wahrscheinlichkeit von Erkrankung und Tod erhöht.', 'Mit zunehmendem Alter nimmt die Elastizität der Blutgefäße ab, was das Risiko für Bluthochdruck erhöht.', 2),
  ('Individuelle Entwicklung', 'Hormonelle Reifung', 'Die durch hormonelle Signale gesteuerte Ausreifung von Organsystemen bis zur vollen Funktions- bzw. Fortpflanzungsfähigkeit, insbesondere während der Pubertät.', 'Die Ausschüttung von Sexualhormonen in der Pubertät löst beim Menschen das Wachstum der Geschlechtsorgane und die Ausbildung sekundärer Geschlechtsmerkmale aus.', 4, 'Pubertät und Geschlechtsreife', 'Der durch das Zusammenspiel von Hypothalamus, Hypophyse und Keimdrüsen gesteuerte Entwicklungsabschnitt, an dessen Ende die Fortpflanzungsfähigkeit steht.', 'Beim Menschen setzt die Pubertät mit dem Einsetzen der Gonadotropin-Ausschüttung der Hypophyse ein und führt u. a. zur ersten Menstruation bzw. Spermienproduktion.', 1),
  ('Individuelle Entwicklung', 'Hormonelle Reifung', 'Die durch hormonelle Signale gesteuerte Ausreifung von Organsystemen bis zur vollen Funktions- bzw. Fortpflanzungsfähigkeit, insbesondere während der Pubertät.', 'Die Ausschüttung von Sexualhormonen in der Pubertät löst beim Menschen das Wachstum der Geschlechtsorgane und die Ausbildung sekundärer Geschlechtsmerkmale aus.', 4, 'Hormonelle Regelkreise der Reifung', 'Rückkopplungsmechanismen zwischen Hypothalamus, Hypophyse und den peripheren Zieldrüsen, die den zeitlichen Ablauf und die Intensität von Reifungsprozessen steuern und regulieren.', 'Ein Anstieg des Sexualhormonspiegels hemmt über negative Rückkopplung die weitere Ausschüttung von Gonadotropinen und hält den Hormonspiegel so in einem charakteristischen Bereich.', 2),
  ('Individuelle Entwicklung', 'Erworbene Anpassungsfähigkeit', 'Die Fähigkeit eines Individuums, seine Struktur, Physiologie oder sein Verhalten im Laufe seiner eigenen Entwicklung an Umweltbedingungen und Erfahrungen anzupassen — anders als evolutionäre Anpassung nicht vererbt, sondern innerhalb einer Lebensspanne erworben.', 'Ein Bergsteiger bildet in großer Höhe innerhalb weniger Wochen mehr rote Blutkörperchen, ohne dass sich sein Genom verändert.', 5, 'Erfahrungsabhängige Plastizität', 'Die Fähigkeit des Nervensystems und des Verhaltens, sich strukturell und funktionell durch individuelle Erfahrung und Übung zu verändern, besonders ausgeprägt in sensiblen Entwicklungsphasen.', 'Bei Kindern, die früh ein Instrument erlernen, ist der für die Feinmotorik der Finger zuständige Hirnrindenbereich stärker ausgebildet als bei Gleichaltrigen ohne diese Erfahrung.', 1),
  ('Individuelle Entwicklung', 'Erworbene Anpassungsfähigkeit', 'Die Fähigkeit eines Individuums, seine Struktur, Physiologie oder sein Verhalten im Laufe seiner eigenen Entwicklung an Umweltbedingungen und Erfahrungen anzupassen — anders als evolutionäre Anpassung nicht vererbt, sondern innerhalb einer Lebensspanne erworben.', 'Ein Bergsteiger bildet in großer Höhe innerhalb weniger Wochen mehr rote Blutkörperchen, ohne dass sich sein Genom verändert.', 5, 'Modifikation', 'Eine nicht erbliche, umweltbedingte Veränderung des Phänotyps innerhalb der durch das Genom vorgegebenen Reaktionsnorm — im Unterschied zur erfahrungsabhängigen Plastizität nicht auf Lernen/Erfahrung beschränkt, sondern jede Form umweltbedingter Phänotypänderung während der Entwicklung.', 'Dieselbe Pflanzenart bildet in praller Sonne kleinere, dickere Blätter aus als im Schatten, obwohl beide Pflanzen genetisch identisch sind.', 2),
  ('Individuelle Entwicklung', 'Erworbene Anpassungsfähigkeit', 'Die Fähigkeit eines Individuums, seine Struktur, Physiologie oder sein Verhalten im Laufe seiner eigenen Entwicklung an Umweltbedingungen und Erfahrungen anzupassen — anders als evolutionäre Anpassung nicht vererbt, sondern innerhalb einer Lebensspanne erworben.', 'Ein Bergsteiger bildet in großer Höhe innerhalb weniger Wochen mehr rote Blutkörperchen, ohne dass sich sein Genom verändert.', 5, 'Lernen und Prägung im Entwicklungsverlauf', 'Verhaltensänderungen durch individuelle Erfahrung, die teils zeitlebens möglich sind (assoziatives Lernen), teils nur in eng begrenzten, sensiblen Phasen der frühen Entwicklung stattfinden können (Prägung).', 'Konrad Lorenz'' Graugänse folgten als Küken demjenigen Objekt, das sie kurz nach dem Schlüpfen zuerst bewegt sahen, und ließen sich später nicht mehr umprägen.', 3),
  ('Individuelle Entwicklung', 'Erworbene Anpassungsfähigkeit', 'Die Fähigkeit eines Individuums, seine Struktur, Physiologie oder sein Verhalten im Laufe seiner eigenen Entwicklung an Umweltbedingungen und Erfahrungen anzupassen — anders als evolutionäre Anpassung nicht vererbt, sondern innerhalb einer Lebensspanne erworben.', 'Ein Bergsteiger bildet in großer Höhe innerhalb weniger Wochen mehr rote Blutkörperchen, ohne dass sich sein Genom verändert.', 5, 'Kompensationsfähigkeit/Regeneration', 'Die Fähigkeit eines Organismus, den Verlust oder die Schädigung von Geweben oder Organen während der individuellen Entwicklung ganz oder teilweise durch Ersatzbildung oder funktionelle Umverteilung auszugleichen.', 'Ein Salamander kann einen verlorenen Schwanz oder ein Bein vollständig neu ausbilden; beim Menschen kann die Leber nach teilweisem Gewebeverlust ihre ursprüngliche Größe weitgehend regenerieren.', 4),
  ('Individuelle Entwicklung', 'Reproduktion', 'Der Abschluss der Individualentwicklung in der Fähigkeit, eigene Nachkommen zu erzeugen — aus Sicht der individuellen Entwicklung der Punkt, an dem sich der Lebenszyklus eines Individuums mit dem der nächsten Generation verknüpft.', 'Mit Erreichen der Geschlechtsreife endet bei vielen Tierarten die Phase des reinen Wachstums, und Energie und Verhalten werden zunehmend auf Paarung und Aufzucht von Nachkommen ausgerichtet.', 6, NULL, NULL, NULL, NULL),
  ('Struktur und Funktion', 'Kompartimentierung', 'Die Unterteilung eines biologischen Systems in räumlich und funktionell abgegrenzte Teilbereiche, wodurch unterschiedliche, teils gegensätzliche Stoffwechselprozesse gleichzeitig und ungestört nebeneinander ablaufen können.', 'Innerhalb einer Zelle trennt die Kompartimentierung in Organellen den sauren Innenraum des Lysosoms vom neutralen Zytoplasma, sodass dessen Verdauungsenzyme nicht die übrige Zelle angreifen.', 1, 'Zelluläre Kompartimentierung (Organellen)', 'Die Unterteilung des Zellinneren durch Membranen in funktionell spezialisierte Zellorganellen.', 'Mitochondrien kompartimentieren die Zellatmung in einem eigenen Innenraum mit einem für die ATP-Synthese notwendigen Protonengradienten.', 1),
  ('Struktur und Funktion', 'Kompartimentierung', 'Die Unterteilung eines biologischen Systems in räumlich und funktionell abgegrenzte Teilbereiche, wodurch unterschiedliche, teils gegensätzliche Stoffwechselprozesse gleichzeitig und ungestört nebeneinander ablaufen können.', 'Innerhalb einer Zelle trennt die Kompartimentierung in Organellen den sauren Innenraum des Lysosoms vom neutralen Zytoplasma, sodass dessen Verdauungsenzyme nicht die übrige Zelle angreifen.', 1, 'Gewebe- und Organebene der Kompartimentierung', 'Die Gliederung eines vielzelligen Organismus in räumlich abgegrenzte Gewebe und Organe mit jeweils spezialisierter Funktion.', 'Der Magen ist durch seine Wand als eigenes Kompartiment abgegrenzt, sodass die stark saure Verdauung dort abläuft, ohne benachbarte Organe zu schädigen.', 2),
  ('Struktur und Funktion', 'Kompartimentierung', 'Die Unterteilung eines biologischen Systems in räumlich und funktionell abgegrenzte Teilbereiche, wodurch unterschiedliche, teils gegensätzliche Stoffwechselprozesse gleichzeitig und ungestört nebeneinander ablaufen können.', 'Innerhalb einer Zelle trennt die Kompartimentierung in Organellen den sauren Innenraum des Lysosoms vom neutralen Zytoplasma, sodass dessen Verdauungsenzyme nicht die übrige Zelle angreifen.', 1, 'Kompartimentierung von Ökosystemen', 'Die räumliche Gliederung von Lebensräumen in unterschiedliche Zonen oder Schichten mit jeweils charakteristischen Umweltbedingungen und Lebensgemeinschaften.', 'Ein See gliedert sich in beleuchtete Freiwasserzone, lichtarme Tiefenzone und Bodenzone, die jeweils von unterschiedlich angepassten Arten besiedelt werden.', 3),
  ('Struktur und Funktion', 'Morphologische und anatomische Angepasstheit', 'Der Zusammenhang zwischen der Gestalt bzw. dem inneren Bau einer Struktur und der Funktion, die sie in ihrer jeweiligen Umwelt erfüllt. Aus diesem Zusammenhang lassen sich Rückschlüsse von der Struktur eines biologischen Merkmals auf seine Funktion ziehen (und umgekehrt).', 'Die Stromlinienform des Delfinkörpers verringert den Strömungswiderstand im Wasser und ermöglicht so eine energieeffiziente Fortbewegung. Auch die dünne, stark gefaltete Oberfläche eines Blattes lässt bereits auf seine Funktion beim Gasaustausch und der Lichtabsorption schließen.', 2, NULL, NULL, NULL, NULL),
  ('Struktur und Funktion', 'Schlüssel-Schloss-Prinzip', 'Das Prinzip der räumlich-strukturellen Passgenauigkeit zwischen zwei Molekülen, durch die eine spezifische, hochselektive Bindung zwischen ihnen ermöglicht wird.', 'Ein Enzym setzt nur ein Substrat um, dessen räumliche Struktur zu seinem aktiven Zentrum passt — wie ein Schlüssel, der nur in ein bestimmtes Schloss passt.', 3, 'Enzym-Substrat-Spezifität', 'Die auf der räumlichen Passung von aktivem Zentrum und Substrat beruhende Fähigkeit eines Enzyms, gezielt nur eine oder wenige chemisch verwandte Reaktionen zu katalysieren.', 'Das Enzym Amylase spaltet Stärke, jedoch nicht die strukturell ähnliche Zellulose, da deren Bindungswinkel nicht in das aktive Zentrum passen.', 1),
  ('Struktur und Funktion', 'Schlüssel-Schloss-Prinzip', 'Das Prinzip der räumlich-strukturellen Passgenauigkeit zwischen zwei Molekülen, durch die eine spezifische, hochselektive Bindung zwischen ihnen ermöglicht wird.', 'Ein Enzym setzt nur ein Substrat um, dessen räumliche Struktur zu seinem aktiven Zentrum passt — wie ein Schlüssel, der nur in ein bestimmtes Schloss passt.', 3, 'Rezeptor-Ligand-Spezifität', 'Die auf räumlicher Passung beruhende spezifische Bindung eines Signalmoleküls (Liganden) an seinen Rezeptor, wodurch nur ein passender Ligand eine zelluläre Antwort auslöst.', 'Insulin bindet spezifisch an den Insulinrezeptor auf der Zelloberfläche und löst dort die Aufnahme von Glukose aus — andere Hormone passen nicht in diesen Rezeptor.', 2),
  ('Struktur und Funktion', 'Oberflächenvergrößerung', 'Das strukturelle Prinzip, durch Faltung, Ausstülpung oder Verzweigung einer Grenzfläche deren Oberfläche im Verhältnis zum umschlossenen Volumen zu vergrößern und dadurch Austauschprozesse zu beschleunigen.', 'Die Dünndarmschleimhaut vergrößert ihre resorbierende Oberfläche durch Falten, Zotten und Mikrovilli um ein Vielfaches gegenüber einer glatten Röhre gleicher Länge.', 4, 'Oberflächenvergrößerung bei Stoffaustausch (Alveolen, Villi)', 'Die Nutzung stark vergrößerter, dünner Austauschflächen zur Beschleunigung von Diffusionsprozessen zwischen zwei Kompartimenten.', 'Die vielen kleinen Lungenbläschen (Alveolen) vergrößern die für den Gasaustausch verfügbare Oberfläche der Lunge auf etwa 100 Quadratmeter.', 1),
  ('Struktur und Funktion', 'Gegenspielerprinzip', 'Das Prinzip, einen physiologischen Zustand durch zwei gegensätzlich wirkende Strukturen oder Signale präzise regulierbar zu machen, statt ihn durch eine einzelne, nur in eine Richtung wirkende Komponente zu steuern.', 'Beuge- und Streckmuskeln eines Gelenks wirken als Gegenspieler (Antagonisten) und ermöglichen dadurch eine präzise, in beide Richtungen steuerbare Bewegung.', 5, 'Muskuläre Antagonisten', 'Muskelpaare, die entgegengesetzte Bewegungen an einem Gelenk bewirken und dadurch eine präzise Steuerung der Gelenkstellung ermöglichen.', 'Bizeps und Trizeps am Oberarm beugen bzw. strecken das Ellenbogengelenk gegenläufig.', 1),
  ('Struktur und Funktion', 'Gegenspielerprinzip', 'Das Prinzip, einen physiologischen Zustand durch zwei gegensätzlich wirkende Strukturen oder Signale präzise regulierbar zu machen, statt ihn durch eine einzelne, nur in eine Richtung wirkende Komponente zu steuern.', 'Beuge- und Streckmuskeln eines Gelenks wirken als Gegenspieler (Antagonisten) und ermöglichen dadurch eine präzise, in beide Richtungen steuerbare Bewegung.', 5, 'Hormonelle Antagonisten', 'Hormonpaare mit entgegengesetzter Wirkung auf denselben physiologischen Parameter, durch deren Zusammenspiel dieser Parameter präzise in einem Sollbereich gehalten werden kann.', 'Insulin senkt den Blutzuckerspiegel, Glucagon erhöht ihn — gemeinsam halten sie den Blutzucker in einem engen Bereich.', 2),
  ('Struktur und Funktion', 'Gegenstromprinzip', 'Ein strukturelles Prinzip, bei dem zwei Flüssigkeitsströme in entgegengesetzter Richtung nah aneinander vorbeigeführt werden, wodurch ein Konzentrations- oder Temperaturgefälle über die gesamte Austauschstrecke aufrechterhalten und der Austausch von Stoffen oder Wärme maximiert wird.', 'Bei Fischkiemen strömt das Blut dem einströmenden Wasser entgegen, wodurch entlang der gesamten Kiemenlamelle ein Sauerstoffgefälle besteht und die Sauerstoffaufnahme maximiert wird.', 6, 'Gegenstromprinzip beim Wärmeaustausch', 'Die Nutzung gegenläufig angeordneter Blutgefäße, um Wärme vom warmen zum kalten Blutstrom zu übertragen und dadurch Wärmeverluste an Körperextremitäten zu verringern.', 'In den Beinen von Watvögeln liegen zu- und abführende Blutgefäße eng beieinander, sodass warmes, herzwärts strömendes Blut das kalte, abwärts strömende Blut vorwärmt und Wärmeverluste über die Beine minimiert werden.', 1),
  ('Struktur und Funktion', 'Gegenstromprinzip', 'Ein strukturelles Prinzip, bei dem zwei Flüssigkeitsströme in entgegengesetzter Richtung nah aneinander vorbeigeführt werden, wodurch ein Konzentrations- oder Temperaturgefälle über die gesamte Austauschstrecke aufrechterhalten und der Austausch von Stoffen oder Wärme maximiert wird.', 'Bei Fischkiemen strömt das Blut dem einströmenden Wasser entgegen, wodurch entlang der gesamten Kiemenlamelle ein Sauerstoffgefälle besteht und die Sauerstoffaufnahme maximiert wird.', 6, 'Gegenstromprinzip beim Stoffaustausch (Kiemenatmung)', 'Die gegenläufige Führung von Blut- und Wasserstrom an der Kiemenoberfläche, durch die ein für die Diffusion günstiges Konzentrationsgefälle über die gesamte Austauschstrecke erhalten bleibt.', 'Fische können durch das Gegenstromprinzip an ihren Kiemen einen deutlich höheren Anteil des im Wasser gelösten Sauerstoffs aufnehmen, als es bei gleichgerichteter Strömung möglich wäre.', 2),
  ('Stoff- und Energieumwandlung', 'Stoffumwandlung', 'Die Aufnahme, chemische Umwandlung, Weiterleitung und Abgabe von Materie durch ein biologisches System im Austausch mit seiner Umwelt.', 'Pflanzen nehmen Kohlenstoffdioxid und Wasser auf und wandeln sie durch Fotosynthese in energiereiche organische Stoffe um.', 1, 'Stoffaustausch mit der Umwelt', 'Die für offene biologische Systeme charakteristische fortlaufende Aufnahme von Stoffen aus der Umwelt und Abgabe von Stoffwechselprodukten an sie.', 'Ein Einzeller nimmt über seine Zellmembran ständig Nährstoffe auf und gibt Stoffwechselendprodukte wie Kohlenstoffdioxid ab.', 1),
  ('Stoff- und Energieumwandlung', 'Stoffumwandlung', 'Die Aufnahme, chemische Umwandlung, Weiterleitung und Abgabe von Materie durch ein biologisches System im Austausch mit seiner Umwelt.', 'Pflanzen nehmen Kohlenstoffdioxid und Wasser auf und wandeln sie durch Fotosynthese in energiereiche organische Stoffe um.', 1, 'Stoffkreislauf', 'Der fortlaufende Umlauf chemischer Elemente zwischen Organismen und ihrer unbelebten Umwelt, bei dem Stoffe wiederholt aufgenommen, umgewandelt und wieder freigesetzt werden.', 'Im Kohlenstoffkreislauf wird Kohlenstoffdioxid von Pflanzen fotosynthetisch gebunden, über Nahrungsketten weitergegeben und durch Zellatmung und Verwesung wieder freigesetzt.', 2),
  ('Stoff- und Energieumwandlung', 'Energieumwandlung', 'Die Aufnahme, Umwandlung, Speicherung und Nutzung von Energie durch ein biologisches System, bei der Energie stets von einer Form in eine andere überführt, aber nie neu erzeugt wird.', 'Bei der Zellatmung wird die in Glukose gespeicherte chemische Energie in die für Zellprozesse nutzbare Energieform ATP umgewandelt.', 2, 'Energieaustausch mit der Umwelt', 'Die fortlaufende Aufnahme von Energie (z. B. Lichtenergie oder in Nahrung gebundene chemische Energie) aus der Umwelt und die Abgabe von Energie (v. a. als Wärme) an sie.', 'Pflanzen nehmen Lichtenergie der Sonne auf, Tiere nehmen chemisch gebundene Energie über die Nahrung auf; beide geben einen Teil der Energie als Wärme wieder ab.', 1),
  ('Stoff- und Energieumwandlung', 'Energieumwandlung', 'Die Aufnahme, Umwandlung, Speicherung und Nutzung von Energie durch ein biologisches System, bei der Energie stets von einer Form in eine andere überführt, aber nie neu erzeugt wird.', 'Bei der Zellatmung wird die in Glukose gespeicherte chemische Energie in die für Zellprozesse nutzbare Energieform ATP umgewandelt.', 2, 'Energiefluss durch Nahrungsketten', 'Die gerichtete Weitergabe von Energie entlang aufeinanderfolgender Nahrungsbeziehungen, beginnend bei den Produzenten.', 'Im Energiefluss einer Wiese wird die von Gräsern gebundene Sonnenenergie über Heuschrecken an Frösche und schließlich an Reiher weitergegeben.', 2),
  ('Stoff- und Energieumwandlung', 'Energieumwandlung', 'Die Aufnahme, Umwandlung, Speicherung und Nutzung von Energie durch ein biologisches System, bei der Energie stets von einer Form in eine andere überführt, aber nie neu erzeugt wird.', 'Bei der Zellatmung wird die in Glukose gespeicherte chemische Energie in die für Zellprozesse nutzbare Energieform ATP umgewandelt.', 2, 'Trophieebenen und Energieverlust', 'Die Gliederung eines Ökosystems in aufeinanderfolgende Ernährungsstufen (Trophieebenen), zwischen denen bei jedem Übergang ein Großteil der Energie als Wärme verloren geht, sodass nur ein kleiner Bruchteil der Energie die nächsthöhere Ebene erreicht.', 'Von der Energie, die Pflanzen binden, steht Pflanzenfressern nur etwa 10 % zur Verfügung, den nachfolgenden Fleischfressern davon wiederum nur etwa 10 %.', 3),
  ('Stoff- und Energieumwandlung', 'Energieumwandlung', 'Die Aufnahme, Umwandlung, Speicherung und Nutzung von Energie durch ein biologisches System, bei der Energie stets von einer Form in eine andere überführt, aber nie neu erzeugt wird.', 'Bei der Zellatmung wird die in Glukose gespeicherte chemische Energie in die für Zellprozesse nutzbare Energieform ATP umgewandelt.', 2, 'Energieentwertung', 'Bei jeder Energieumwandlung geht ein Teil der Energie als für biologische Arbeit nicht mehr nutzbare Wärme verloren (2. Hauptsatz der Thermodynamik), wodurch Lebewesen auf einen kontinuierlichen Energienachschub angewiesen sind.', 'Nur ein Teil der in der Nahrung enthaltenen chemischen Energie wird von einem Tier in Wachstum umgesetzt, ein erheblicher Anteil geht als Stoffwechselwärme verloren.', 4),
  ('Stoff- und Energieumwandlung', 'Energieumwandlung', 'Die Aufnahme, Umwandlung, Speicherung und Nutzung von Energie durch ein biologisches System, bei der Energie stets von einer Form in eine andere überführt, aber nie neu erzeugt wird.', 'Bei der Zellatmung wird die in Glukose gespeicherte chemische Energie in die für Zellprozesse nutzbare Energieform ATP umgewandelt.', 2, 'Energetische Kopplung', 'Die Verknüpfung einer energieliefernden mit einer energieverbrauchenden Reaktion, sodass die insgesamt frei werdende Energie einen sonst nicht ablaufenden Prozess antreiben kann.', 'Die energieliefernde Spaltung von ATP zu ADP ist an die energieverbrauchende Kontraktion von Muskelfilamenten gekoppelt; ebenso sind bei der Zellatmung Redoxreaktionen an die ATP-Synthese gekoppelt.', 5),
  ('Stoff- und Energieumwandlung', 'Fließgleichgewicht', 'Ein für offene, lebende Systeme charakteristischer Zustand, in dem sich Zu- und Abfluss von Stoffen und Energie die Waage halten, sodass innere Zustandsgrößen konstant bleiben, obwohl fortlaufend Materie und Energie durch das System hindurchfließen — im Unterschied zu einem geschlossenen System, das einem statischen Gleichgewicht zustrebt.', 'Der Wassergehalt des menschlichen Körpers bleibt trotz ständiger Wasseraufnahme und -abgabe nahezu konstant, weil Zufuhr und Ausscheidung fortlaufend aneinander angeglichen werden.', 3, NULL, NULL, NULL, NULL),
  ('Information und Kommunikation', 'Signaltransduktion', 'Die Umwandlung eines extrazellulären Signals in eine intrazelluläre Antwort durch eine Kette molekularer Ereignisse, ausgelöst durch die Bindung eines Signalmoleküls an einen spezifischen Rezeptor.', 'Bindet Adrenalin an seinen Rezeptor auf einer Leberzelle, löst dies über eine Signalkaskade den Abbau von Glykogen zu Glukose aus.', 1, 'Rezeptor-vermittelte Signalübertragung', 'Die spezifische Erkennung eines Signalmoleküls durch einen passenden Rezeptor als erster Schritt jeder Signaltransduktion.', 'Membranständige Rezeptoren erkennen wasserlösliche Hormone wie Insulin, die die Zellmembran selbst nicht durchqueren können.', 1),
  ('Information und Kommunikation', 'Signaltransduktion', 'Die Umwandlung eines extrazellulären Signals in eine intrazelluläre Antwort durch eine Kette molekularer Ereignisse, ausgelöst durch die Bindung eines Signalmoleküls an einen spezifischen Rezeptor.', 'Bindet Adrenalin an seinen Rezeptor auf einer Leberzelle, löst dies über eine Signalkaskade den Abbau von Glykogen zu Glukose aus.', 1, 'Second-Messenger-Systeme', 'Intrazelluläre Botenstoffe, die ein an der Zelloberfläche empfangenes Signal ins Zellinnere weiterleiten und dabei häufig verstärken.', 'Nach der Bindung von Adrenalin an seinen Rezeptor steigt die Konzentration des second messenger cAMP im Zellinneren stark an und aktiviert dort weitere Enzyme.', 2),
  ('Information und Kommunikation', 'Codierung und Decodierung von Information', 'Die Übersetzung von Information von einer Darstellungsform in eine andere nach festen Regeln — etwa von einer Nukleotidsequenz in eine Aminosäuresequenz oder von einem physikalischen Reiz in ein neuronales Signalmuster.', 'Der genetische Code übersetzt die Basensequenz der mRNA nach einem festen Codewörter-Schema in die Aminosäuresequenz eines Proteins.', 2, 'Genetischer Code (Transkription/Translation)', 'Die Umschrift der genetischen Information von der DNA in mRNA (Transkription) und deren anschließende Übersetzung in eine Aminosäuresequenz (Translation) nach dem universellen Basentriplett-Code.', 'Das Basentriplett GUU wird stets in die Aminosäure Valin übersetzt — unabhängig davon, ob es sich um eine Bakterien- oder eine menschliche Zelle handelt.', 1),
  ('Information und Kommunikation', 'Codierung und Decodierung von Information', 'Die Übersetzung von Information von einer Darstellungsform in eine andere nach festen Regeln — etwa von einer Nukleotidsequenz in eine Aminosäuresequenz oder von einem physikalischen Reiz in ein neuronales Signalmuster.', 'Der genetische Code übersetzt die Basensequenz der mRNA nach einem festen Codewörter-Schema in die Aminosäuresequenz eines Proteins.', 2, 'Neuronale Codierung von Reizen', 'Die Umwandlung physikalischer oder chemischer Reizeigenschaften (z. B. Reizstärke) in ein Muster elektrischer Nervenimpulse, das im Nervensystem weiterverarbeitet werden kann.', 'Ein stärkerer Druckreiz auf der Haut wird nicht durch größere, sondern durch häufigere Aktionspotenziale in der zuführenden Nervenfaser codiert.', 2),
  ('Information und Kommunikation', 'Kommunikation zwischen Organismen', 'Der Austausch von Signalen zwischen Individuen derselben oder verschiedener Arten, durch den das Verhalten des Empfängers zugunsten (meist) des Senders beeinflusst wird.', 'Bienen teilen sich durch den Schwänzeltanz die Richtung und Entfernung einer Futterquelle mit.', 3, 'Chemische Kommunikation (Pheromone)', 'Die Verständigung zwischen Individuen mittels artspezifischer chemischer Botenstoffe (Pheromone), die über die Luft oder das Wasser wahrgenommen werden.', 'Weibliche Nachtfalter locken paarungsbereite Männchen durch die Abgabe von Sexualpheromonen über mehrere hundert Meter an.', 1),
  ('Information und Kommunikation', 'Kommunikation zwischen Organismen', 'Der Austausch von Signalen zwischen Individuen derselben oder verschiedener Arten, durch den das Verhalten des Empfängers zugunsten (meist) des Senders beeinflusst wird.', 'Bienen teilen sich durch den Schwänzeltanz die Richtung und Entfernung einer Futterquelle mit.', 3, 'Akustische und visuelle Kommunikation', 'Die Verständigung zwischen Individuen mittels Lauten oder optischer Signale wie Körperhaltung, Farbe oder Bewegung.', 'Vogelgesang markiert Reviergrenzen und signalisiert Paarungsbereitschaft; das Balzverhalten des Pfaus wirkt über sein auffälliges Rad visuell.', 2),
  ('Information und Kommunikation', 'Kommunikation zwischen Organismen', 'Der Austausch von Signalen zwischen Individuen derselben oder verschiedener Arten, durch den das Verhalten des Empfängers zugunsten (meist) des Senders beeinflusst wird.', 'Bienen teilen sich durch den Schwänzeltanz die Richtung und Entfernung einer Futterquelle mit.', 3, 'Soziale Signalsysteme', 'Komplexe, oft aus mehreren Signalkanälen zusammengesetzte Kommunikationssysteme, die soziale Beziehungen innerhalb einer Gruppe regeln, etwa Rangordnung, Zusammenhalt oder Warnung vor Gefahr.', 'Erdmännchen geben unterschiedliche Warnrufe für Gefahr aus der Luft und vom Boden ab, auf die Artgenossen jeweils mit einem passenden Fluchtverhalten reagieren.', 3),
  ('Information und Kommunikation', 'Kommunikation innerhalb eines Organismus', 'Der Austausch von Signalen zwischen Zellen, Geweben und Organen innerhalb eines vielzelligen Organismus, durch den dessen Aktivitäten koordiniert werden.', 'Nervensystem und Hormonsystem sorgen gemeinsam dafür, dass Herzschlag, Atmung und Verdauung eines Organismus aufeinander abgestimmt ablaufen.', 4, 'Nervale Kommunikation (Synapsen, Aktionspotenzial)', 'Die schnelle, elektrisch-chemische Signalübertragung zwischen Nervenzellen über Aktionspotenziale und Synapsen.', 'Ein Aktionspotenzial wandert entlang eines Axons zur Synapse, löst dort die Ausschüttung von Neurotransmittern aus und überträgt das Signal auf die nächste Zelle.', 1),
  ('Information und Kommunikation', 'Kommunikation innerhalb eines Organismus', 'Der Austausch von Signalen zwischen Zellen, Geweben und Organen innerhalb eines vielzelligen Organismus, durch den dessen Aktivitäten koordiniert werden.', 'Nervensystem und Hormonsystem sorgen gemeinsam dafür, dass Herzschlag, Atmung und Verdauung eines Organismus aufeinander abgestimmt ablaufen.', 4, 'Hormonelle Kommunikation (endokrines System)', 'Die langsamere, über die Blutbahn vermittelte Signalübertragung durch Hormone, die an entfernten Zielzellen mit passenden Rezeptoren wirken.', 'Die Bauchspeicheldrüse gibt Insulin ins Blut ab, das über den gesamten Körper verteilt wird und an Muskel-, Leber- und Fettzellen die Glukoseaufnahme auslöst.', 2),
  ('Information und Kommunikation', 'Reizaufnahme und Reizverarbeitung', 'Die Aufnahme physikalischer oder chemischer Umweltreize durch spezialisierte Sinneszellen und ihre anschließende Weiterleitung und Verarbeitung im Nervensystem bis zur bewussten Wahrnehmung oder unwillkürlichen Reaktion.', 'Lichtreize werden von den Sinneszellen der Netzhaut aufgenommen, als Nervenimpulse über den Sehnerv weitergeleitet und im Gehirn zu einem Bild verarbeitet.', 5, 'Sinnesorgane und Rezeptortypen', 'Spezialisierte Organe und Zellen, die auf bestimmte Reizarten (Licht, Schall, Druck, Chemikalien u. a.) besonders empfindlich reagieren und diese in Nervenerregung umsetzen.', 'Das Auge enthält Fotorezeptoren für Licht, das Ohr Mechanorezeptoren für Schallwellen, die Zunge Chemorezeptoren für gelöste Stoffe.', 1),
  ('Information und Kommunikation', 'Reizaufnahme und Reizverarbeitung', 'Die Aufnahme physikalischer oder chemischer Umweltreize durch spezialisierte Sinneszellen und ihre anschließende Weiterleitung und Verarbeitung im Nervensystem bis zur bewussten Wahrnehmung oder unwillkürlichen Reaktion.', 'Lichtreize werden von den Sinneszellen der Netzhaut aufgenommen, als Nervenimpulse über den Sehnerv weitergeleitet und im Gehirn zu einem Bild verarbeitet.', 5, 'Reizweiterleitung und zentrale Verarbeitung', 'Die Weiterleitung der in Sinneszellen entstandenen Erregung über afferente Nervenbahnen zum zentralen Nervensystem und deren dortige Verrechnung mit anderen Signalen.', 'Signale mehrerer Geschmacksknospen der Zunge werden im Gehirn zu einem einzigen zusammengesetzten Geschmackseindruck verarbeitet.', 2),
  ('Steuerung und Regelung', 'Steuerung', 'Die Beeinflussung eines Prozesses durch ein Eingangssignal ohne Rückmeldung des erzielten Ergebnisses an den Ausgangspunkt (offener Wirkungskreis) — im Unterschied zur Regelung erfolgt keine fortlaufende Korrektur anhand des tatsächlichen Ergebnisses.', 'Ein genetisches Entwicklungsprogramm steuert den Ablauf der Embryonalentwicklung nach einem festen Zeitplan, unabhängig davon, ob jeder Einzelschritt exakt gelingt.', 1, 'Offener Wirkungskreis (Steuerkette)', 'Eine Wirkungskette, bei der ein Eingangssignal über mehrere Stationen zu einem Ausgangssignal führt, ohne dass das Ergebnis auf den Anfang der Kette zurückwirkt.', 'Ein Reflex wie das Zurückziehen der Hand von einer heißen Herdplatte läuft als feste Steuerkette ab, ohne dass das Ergebnis der Bewegung den auslösenden Reiz beeinflusst.', 1),
  ('Steuerung und Regelung', 'Steuerung', 'Die Beeinflussung eines Prozesses durch ein Eingangssignal ohne Rückmeldung des erzielten Ergebnisses an den Ausgangspunkt (offener Wirkungskreis) — im Unterschied zur Regelung erfolgt keine fortlaufende Korrektur anhand des tatsächlichen Ergebnisses.', 'Ein genetisches Entwicklungsprogramm steuert den Ablauf der Embryonalentwicklung nach einem festen Zeitplan, unabhängig davon, ob jeder Einzelschritt exakt gelingt.', 1, 'Vorprogrammierte/genetisch determinierte Steuerungsprozesse', 'Entwicklungs- oder Verhaltensabläufe, die durch ein genetisch festgelegtes Programm gesteuert werden und weitgehend unabhängig von einer laufenden Rückmeldung ablaufen.', 'Das Nestbauverhalten vieler Vogelarten folgt einem angeborenen, artspezifischen Bewegungsmuster, das auch bei erstmals brütenden Tieren ohne vorherige Erfahrung abläuft.', 2),
  ('Steuerung und Regelung', 'Steuerung', 'Die Beeinflussung eines Prozesses durch ein Eingangssignal ohne Rückmeldung des erzielten Ergebnisses an den Ausgangspunkt (offener Wirkungskreis) — im Unterschied zur Regelung erfolgt keine fortlaufende Korrektur anhand des tatsächlichen Ergebnisses.', 'Ein genetisches Entwicklungsprogramm steuert den Ablauf der Embryonalentwicklung nach einem festen Zeitplan, unabhängig davon, ob jeder Einzelschritt exakt gelingt.', 1, 'Reizaufnahme und Reizverarbeitung', 'Die Aufnahme eines äußeren oder inneren Reizes als Auslöser, der einen Steuerungsprozess in Gang setzt.', 'Die Wahrnehmung von Dunkelheit durch die Netzhaut löst beim Menschen die Ausschüttung des Schlafhormons Melatonin aus.', 3),
  ('Steuerung und Regelung', 'Regelung', 'Die Beeinflussung eines Prozesses in einem geschlossenen Wirkungskreis, bei dem die tatsächliche Zustandsgröße fortlaufend gemessen, mit einem Sollwert verglichen und bei Abweichung korrigierend nachgesteuert wird.', 'Die Regelung der Körpertemperatur vergleicht fortlaufend die gemessene Temperatur mit einem Sollwert von etwa 37 °C und löst bei Abweichung Gegenmaßnahmen wie Schwitzen oder Zittern aus.', 2, 'Regelkreis-Struktur (Sollwert, Regler, Regelgröße, Istwert)', 'Der grundlegende Aufbau eines Regelkreises aus Sollwert (Zielzustand), Regler (vergleichende und steuernde Instanz), Regelgröße/Istwert (tatsächlich gemessener Zustand) und einer Rückkopplungsschleife zwischen ihnen.', 'Beim Blutzuckerregelkreis ist die Bauchspeicheldrüse der Regler, der Blutzuckerspiegel die Regelgröße und ein enger Normbereich der Sollwert.', 1),
  ('Steuerung und Regelung', 'Regelung', 'Die Beeinflussung eines Prozesses in einem geschlossenen Wirkungskreis, bei dem die tatsächliche Zustandsgröße fortlaufend gemessen, mit einem Sollwert verglichen und bei Abweichung korrigierend nachgesteuert wird.', 'Die Regelung der Körpertemperatur vergleicht fortlaufend die gemessene Temperatur mit einem Sollwert von etwa 37 °C und löst bei Abweichung Gegenmaßnahmen wie Schwitzen oder Zittern aus.', 2, 'Negative Rückkopplung (inkl. Homöostase-Prinzip)', 'Eine Rückkopplung, bei der eine Abweichung von einem Sollwert eine Gegenreaktion auslöst, die diese Abweichung verringert — der zentrale Mechanismus, durch den biologische Systeme innere Zustände in engen Grenzen konstant halten (Homöostase).', 'Steigt die Körpertemperatur über den Sollwert, wird durch Schwitzen Wärme abgegeben, bis die Temperatur wieder sinkt — ein klassisches Beispiel für negative Rückkopplung und Homöostase.', 2),
  ('Steuerung und Regelung', 'Regelung', 'Die Beeinflussung eines Prozesses in einem geschlossenen Wirkungskreis, bei dem die tatsächliche Zustandsgröße fortlaufend gemessen, mit einem Sollwert verglichen und bei Abweichung korrigierend nachgesteuert wird.', 'Die Regelung der Körpertemperatur vergleicht fortlaufend die gemessene Temperatur mit einem Sollwert von etwa 37 °C und löst bei Abweichung Gegenmaßnahmen wie Schwitzen oder Zittern aus.', 2, 'Positive Rückkopplung', 'Eine Rückkopplung, bei der eine Abweichung von einem Ausgangszustand eine Reaktion auslöst, die diese Abweichung weiter verstärkt, statt sie auszugleichen — anders als negative Rückkopplung nicht stabilisierend, sondern selbstverstärkend, meist zeitlich begrenzt bis zu einem definierten Endpunkt.', 'Bei der Geburt verstärken die Wehen durch Ausschüttung von Oxytocin sich selbst immer weiter, bis das Kind geboren ist und die Rückkopplungsschleife endet.', 3),
  ('Steuerung und Regelung', 'Regelung', 'Die Beeinflussung eines Prozesses in einem geschlossenen Wirkungskreis, bei dem die tatsächliche Zustandsgröße fortlaufend gemessen, mit einem Sollwert verglichen und bei Abweichung korrigierend nachgesteuert wird.', 'Die Regelung der Körpertemperatur vergleicht fortlaufend die gemessene Temperatur mit einem Sollwert von etwa 37 °C und löst bei Abweichung Gegenmaßnahmen wie Schwitzen oder Zittern aus.', 2, 'Adaptation und Gewöhnung', 'Die allmähliche Abnahme der Empfindlichkeit eines Sinnesrezeptors oder Nervensystems bei anhaltender oder wiederholter Reizung.', 'Nach einiger Zeit im selben Raum wird ein anfangs auffälliger Geruch kaum noch wahrgenommen, da sich die Riechrezeptoren an den gleichbleibenden Reiz gewöhnt haben.', 4),
  ('Steuerung und Regelung', 'Regelung', 'Die Beeinflussung eines Prozesses in einem geschlossenen Wirkungskreis, bei dem die tatsächliche Zustandsgröße fortlaufend gemessen, mit einem Sollwert verglichen und bei Abweichung korrigierend nachgesteuert wird.', 'Die Regelung der Körpertemperatur vergleicht fortlaufend die gemessene Temperatur mit einem Sollwert von etwa 37 °C und löst bei Abweichung Gegenmaßnahmen wie Schwitzen oder Zittern aus.', 2, 'Fließgleichgewicht', 'Der durch Regelungsprozesse aufrechterhaltene Zustand, in dem Zu- und Abfluss von Stoffen oder Energie trotz schwankender äußerer Bedingungen fortlaufend so aneinander angeglichen werden, dass innere Zustandsgrößen annähernd konstant bleiben.', 'Der Wasserhaushalt des Körpers wird durch die Regelung der Urinausscheidung an schwankende Trinkmengen angepasst, sodass der Wassergehalt des Körpers annähernd konstant bleibt.', 5);

  -- One Ebene-1 row per distinct (root_label, e1_label) -- find-or-create,
  -- then always refresh definition from the source text (metadata carries
  -- the worked example, same convention as every other EvoMentor_DE
  -- harvest in this repo keeping rich prose out of the plain label).
  FOR r IN SELECT DISTINCT root_label, e1_label, e1_def, e1_ex, e1_order FROM _concept_import LOOP
    SELECT id INTO v_root_id FROM lpm_schema_elements WHERE project_id = v_project_id AND parent_id IS NULL AND label = r.root_label;
    IF v_root_id IS NULL THEN CONTINUE; END IF;

    SELECT id INTO v_e1_id FROM lpm_schema_elements WHERE project_id = v_project_id AND parent_id = v_root_id AND label = r.e1_label;
    IF v_e1_id IS NULL THEN
      INSERT INTO lpm_schema_elements (project_id, element_type, label, parent_id, status, definition, metadata)
      VALUES (v_project_id, 'concept', r.e1_label, v_root_id, 'accepted', r.e1_def, jsonb_build_object('beispiel', r.e1_ex, 'reihenfolge', r.e1_order, 'source', 'evomentor_de_data_2026_10_01'))
      RETURNING id INTO v_e1_id;
    ELSE
      UPDATE lpm_schema_elements SET definition = r.e1_def, metadata = metadata || jsonb_build_object('beispiel', r.e1_ex, 'reihenfolge', r.e1_order, 'source', 'evomentor_de_data_2026_10_01')
      WHERE id = v_e1_id;
    END IF;
  END LOOP;

  -- Ebene-2 rows, nested under their real Ebene-1 parent found above.
  FOR r IN SELECT * FROM _concept_import WHERE e2_label IS NOT NULL LOOP
    SELECT id INTO v_root_id FROM lpm_schema_elements WHERE project_id = v_project_id AND parent_id IS NULL AND label = r.root_label;
    IF v_root_id IS NULL THEN CONTINUE; END IF;
    SELECT id INTO v_e1_id FROM lpm_schema_elements WHERE project_id = v_project_id AND parent_id = v_root_id AND label = r.e1_label;
    IF v_e1_id IS NULL THEN CONTINUE; END IF;

    IF EXISTS (SELECT 1 FROM lpm_schema_elements WHERE project_id = v_project_id AND parent_id = v_e1_id AND label = r.e2_label) THEN
      UPDATE lpm_schema_elements SET definition = r.e2_def, metadata = metadata || jsonb_build_object('beispiel', r.e2_ex, 'reihenfolge', r.e2_order, 'source', 'evomentor_de_data_2026_10_01')
      WHERE project_id = v_project_id AND parent_id = v_e1_id AND label = r.e2_label;
    ELSE
      INSERT INTO lpm_schema_elements (project_id, element_type, label, parent_id, status, definition, metadata)
      VALUES (v_project_id, 'concept', r.e2_label, v_e1_id, 'accepted', r.e2_def, jsonb_build_object('beispiel', r.e2_ex, 'reihenfolge', r.e2_order, 'source', 'evomentor_de_data_2026_10_01'));
    END IF;
  END LOOP;
END $$;
